jwt:
  secret: afklqjehwflknslkfvnlkaengawoerngoaiwngoipwrjepajkfladskflmlvkznmlknaewrgfhewaroiptjaipgojwrgdasfkjnasfjenfpoiawn

spring:
  data:
    redis:
      host: localhost
      port: 6379
  profiles:
    active:
      - dev
