jwt:
  secret: afklqjehwflknslkfvnlkaengawoerngoaiwngoipwrjepajkfladskflmlvkznmlknaewrgfhewaroiptjaipgojwrgdasfkjnasfjenfpoiawn

spring:

  mail:
    # Google smtp server 사용
    host: smtp.gmail.com
    port: 587
    username: paramtestt@gmail.com #앱 비밀번호 발급받은 google 계정
    password: zoms hbtp sdtf lmku
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
  data:
    redis:
      host: localhost
      port: 6379
  profiles:
    active:
      - dev
